### ISSUE TITLE
Desarrollo [SEMANA 3]

### ISSUE THREAD

**Issue by Sax16** [NoeMelo/HimnarioMMM#21]
Se agregaran nuevos Coros e Himnos hasta el **04/02/22**

**Comment by NoeMelo** [comment]
Hola @Sax16 , Dios te bendiga.

Tengo unos inconvenientes para terminar las tareas, en dos semanas aprox estaré más libre para poder continuar.


Saludos,

**Comment by Sax16** [comment]
No te preocupes mi Hno. @NoeMelo 

Estaré avanzando localmente con los archivos y las imágenes.

Dios te bendiga.

**Comment by NoeMelo** [comment]
Se hizo merge de los cambios a master
